Create Table PERSONWSPFINAL(
PID INT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(64),
PASSWORD VARCHAR(64),
PRIMARY KEY(PID)
);

Insert into PERSONWSPFINAL (USERNAME, PASSWORD)
    VALUES('Qing', 'password');

